/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#f6be39',
        'tertiary-fixed': '#e2e2e2',
        error: '#ba1a1a',
        'on-secondary-container': '#616365',
        'surface-tint': '#795900',
        'on-tertiary': '#ffffff',
        'primary-container': '#d4a017',
        'on-tertiary-fixed': '#1a1c1c',
        'on-primary-container': '#503a00',
        primary: '#795900',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#ffdfa0',
        'on-secondary-fixed-variant': '#454749',
        'on-surface': '#1c1b1b',
        'surface-container-low': '#f6f3f2',
        'surface-dim': '#dcd9d9',
        tertiary: '#5d5f5f',
        'on-primary-fixed': '#261a00',
        'on-secondary-fixed': '#1a1c1d',
        surface: '#fcf9f8',
        'inverse-on-surface': '#f3f0ef',
        'surface-container-high': '#eae7e7',
        'secondary-container': '#dfdfe1',
        'tertiary-container': '#a7a8a8',
        'on-tertiary-container': '#3c3d3e',
        'error-container': '#ffdad6',
        outline: '#817662',
        'surface-variant': '#e5e2e1',
        'on-error-container': '#93000a',
        'on-background': '#1c1b1b',
        'on-surface-variant': '#4f4634',
        'on-secondary': '#ffffff',
        'inverse-primary': '#f6be39',
        'on-error': '#ffffff',
        'outline-variant': '#d3c5ae',
        'tertiary-fixed-dim': '#c6c6c6',
        'secondary-fixed': '#e2e2e4',
        'surface-container-highest': '#e5e2e1',
        'secondary-fixed-dim': '#c6c6c8',
        'on-primary-fixed-variant': '#5c4300',
        'surface-container': '#f0eded',
        'on-tertiary-fixed-variant': '#454747',
        'on-primary': '#ffffff',
        background: '#fcf9f8',
        secondary: '#5d5e60',
        'surface-bright': '#fcf9f8',
        'inverse-surface': '#313030',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-padding': '120px',
        'margin-desktop': '80px',
        gutter: '24px',
        'margin-mobile': '20px',
        'container-max': '1440px',
        unit: '8px',
      },
      fontFamily: {
        'display-lg': ['Bodoni Moda', 'serif'],
        'headline-xl-mobile': ['Bodoni Moda', 'serif'],
        'headline-md': ['Bodoni Moda', 'serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Bodoni Moda', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['80px', { lineHeight: '90px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['40px', { lineHeight: '48px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['56px', { lineHeight: '64px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
